name: Metview-Python
channels:
  - conda-forge
dependencies:
  - metview-batch
  - metview-python
  - os
  - numpy
  - numpy.polynomial.polynomial
  - pandas
  - datetime
  - matplotlib
  - scipy
  - scipy.stats
  - sklearn.metrics
